services:
  github-inviter:
    container_name: github-inviter
    image: ghcr.io/frostwalk/github-inviter:latest
    environment:
      - GITHUB_ORG_NAME=github-org-name
      - GITHUB_TOKEN=github-token
      - GITHUB_GROUP_NAME=github-org-group
      - INVITE_CODE=secret-code
      - PORT=8080
      # Uncomment the following lines if you want to use TLS
      #- TLS_CERT=/cert.pem
      #- TLS_KEY=/key.pem
    ports:
      - "8080:8080"
    # Uncomment the following lines if you want to use TLS
    #volumes:
    #  - /home/federico/ca.pem:/cert.pem:ro
    #  - /home/federico/ca.key:/key.pem:ro